#!/usr/bin/env python3
"""Run a real HunyuanImage3 request and build a MoE routing page."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_PROMPT = "生成一张复杂的咖啡图"
DEFAULT_MODEL = "tencent/HunyuanImage-3.0-Instruct"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--prompt", default=DEFAULT_PROMPT)
    parser.add_argument("--output-root", default=None)
    parser.add_argument("--height", type=int, default=1024)
    parser.add_argument("--width", type=int, default=1024)
    parser.add_argument("--steps", type=int, default=10)
    parser.add_argument("--guidance-scale", type=float, default=0.0)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--ar-devices", default="0,1")
    parser.add_argument("--dit-devices", default="2,3")
    parser.add_argument("--ar-tp", type=int, default=2)
    parser.add_argument("--dit-tp", type=int, default=2)
    parser.add_argument("--ar-gpu-memory-utilization", type=float, default=0.80)
    parser.add_argument("--ar-max-model-len", type=int, default=8192)
    parser.add_argument("--ar-max-num-batched-tokens", type=int, default=8192)
    parser.add_argument("--connector-port", type=int, default=50051)
    parser.add_argument("--init-timeout", type=int, default=900)
    parser.add_argument("--publish-dir", default=None)
    parser.add_argument("--rank-policy", choices=["rank0", "all"], default="rank0")
    return parser.parse_args()


def repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def repo_python(root: Path) -> str:
    venv_python = root / ".venv" / "bin" / "python"
    return str(venv_python) if venv_python.exists() else sys.executable


def write_stage_config(path: Path, args: argparse.Namespace) -> None:
    path.write_text(
        f"""# Auto-generated by docs/uad/script/profile_hunyuan_real_request_routing.py
stage_args:
  - stage_id: 0
    stage_type: llm
    runtime:
      process: true
      devices: "{args.ar_devices}"
      max_batch_size: 1
      requires_multimodal_data: false
    engine_args:
      model_stage: AR
      model_arch: HunyuanImage3ForCausalMM
      worker_cls: vllm_omni.worker.gpu_ar_worker.GPUARWorker
      scheduler_cls: vllm_omni.core.sched.omni_ar_scheduler.OmniARScheduler
      gpu_memory_utilization: {args.ar_gpu_memory_utilization}
      enforce_eager: true
      trust_remote_code: true
      engine_output_type: latent
      enable_prefix_caching: false
      max_model_len: {args.ar_max_model_len}
      max_num_batched_tokens: {args.ar_max_num_batched_tokens}
      tensor_parallel_size: {args.ar_tp}
      pipeline_parallel_size: 1
      hf_overrides:
        rope_parameters:
          mrope_section: [0, 32, 32]
          rope_type: default
      omni_kv_config:
        need_send_cache: true
    is_comprehension: false
    final_output: true
    final_output_type: text
    default_sampling_params:
      temperature: 0.0
      top_p: 1
      top_k: -1
      max_tokens: {args.ar_max_model_len}
      stop_token_ids: [128025]
      detokenize: true
      skip_special_tokens: false
    output_connectors:
      to_stage_1: rdma_connector

  - stage_id: 1
    stage_type: diffusion
    runtime:
      process: true
      devices: "{args.dit_devices}"
      max_batch_size: 1
      requires_multimodal_data: false
    engine_args:
      model_stage: dit
      model_arch: HunyuanImage3ForCausalMM
      enforce_eager: true
      trust_remote_code: true
      distributed_executor_backend: "mp"
      omni_kv_config:
        need_recv_cache: true
      parallel_config:
        tensor_parallel_size: {args.dit_tp}
        enable_expert_parallel: true
    engine_input_source: [0]
    custom_process_input_func: vllm_omni.model_executor.stage_input_processors.hunyuan_image3.ar2diffusion
    final_output: true
    final_output_type: image
    default_sampling_params:
      num_inference_steps: {args.steps}
      guidance_scale: {args.guidance_scale}
    input_connectors:
      from_stage_0: rdma_connector

runtime:
  enabled: true
  connectors:
    rdma_connector:
      name: MooncakeTransferEngineConnector
      extra:
        host: "auto"
        zmq_port: {args.connector_port}
        protocol: "rdma"
        device_name: ""
        memory_pool_size: 4294967296
        memory_pool_device: "cpu"
  edges:
    - from: 0
      to: 1
""",
        encoding="utf-8",
    )


def copy_publish(output_root: Path, publish_dir: Path) -> None:
    publish_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(output_root / "hunyuan_real_request_routing.html", publish_dir / "index.html")
    shutil.copy2(output_root / "route_report.json", publish_dir / "route_report.json")
    image_src_dir = output_root / "images"
    if image_src_dir.exists():
        image_dst_dir = publish_dir / "images"
        if image_dst_dir.exists():
            shutil.rmtree(image_dst_dir)
        shutil.copytree(image_src_dir, image_dst_dir)


def run_generation_with_trace_capture(
    cmd: list[str],
    *,
    cwd: Path,
    env: dict[str, str],
    log_path: Path,
    capture_file: Path,
) -> int:
    """Run generation and enable route tracing after engine warmup.

    vLLM executes profiling/warmup forwards before serving the real request.
    AR MoE tracing lives inside the model block, so without this gate those
    warmup tokens are indistinguishable from real request tokens in the trace.
    """

    marker = "HunyuanImage-3.0 Generation Configuration:"
    if capture_file.exists():
        capture_file.unlink()

    with log_path.open("w", encoding="utf-8") as log:
        proc = subprocess.Popen(
            cmd,
            cwd=cwd,
            env=env,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            bufsize=1,
        )
        assert proc.stdout is not None
        capture_enabled = False
        for line in proc.stdout:
            log.write(line)
            log.flush()
            if not capture_enabled and marker in line:
                capture_file.write_text("capture real request\n", encoding="utf-8")
                capture_enabled = True
        return proc.wait()


def main() -> None:
    args = parse_args()
    root = repo_root()
    if args.output_root is None:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        output_root = root / "artifacts" / "uad_real_request_routing" / stamp
    else:
        output_root = Path(args.output_root).resolve()
    output_root.mkdir(parents=True, exist_ok=True)

    trace_dir = output_root / "trace"
    image_dir = output_root / "images"
    trace_dir.mkdir(parents=True, exist_ok=True)
    image_dir.mkdir(parents=True, exist_ok=True)

    stage_config = output_root / "hunyuan_image3_t2i_2p2_route_trace.yaml"
    write_stage_config(stage_config, args)
    python_exe = repo_python(root)

    env = os.environ.copy()
    env["HUNYUAN_MOE_ROUTE_TRACE_DIR"] = str(trace_dir)
    capture_file = output_root / "trace_capture.enabled"
    env["HUNYUAN_MOE_ROUTE_TRACE_CAPTURE_FILE"] = str(capture_file)
    env.setdefault("CUDA_DEVICE_ORDER", "PCI_BUS_ID")
    env.setdefault("PYTHONUNBUFFERED", "1")
    env.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
    env["PYTHONPATH"] = str(root) + (os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else "")

    cmd = [
        python_exe,
        "examples/offline_inference/hunyuan_image3/end2end.py",
        "--model",
        args.model,
        "--modality",
        "text2img",
        "--stage-configs-path",
        str(stage_config),
        "--prompts",
        args.prompt,
        "--steps",
        str(args.steps),
        "--guidance-scale",
        str(args.guidance_scale),
        "--height",
        str(args.height),
        "--width",
        str(args.width),
        "--seed",
        str(args.seed),
        "--output",
        str(image_dir),
        "--init-timeout",
        str(args.init_timeout),
        "--enforce-eager",
    ]

    log_path = output_root / "generation.log"
    print("Running:", " ".join(cmd), flush=True)
    returncode = run_generation_with_trace_capture(
        cmd,
        cwd=root,
        env=env,
        log_path=log_path,
        capture_file=capture_file,
    )
    if returncode != 0:
        tail = log_path.read_text(errors="replace")[-4000:]
        raise SystemExit(f"HunyuanImage3 request failed with code {returncode}. Log tail:\n{tail}")

    image_url = ""
    images = sorted(image_dir.glob("output_*.png"))
    if images:
        image_url = "images/" + images[0].name

    html_path = output_root / "hunyuan_real_request_routing.html"
    json_path = output_root / "route_report.json"
    build_cmd = [
        python_exe,
        "docs/uad/script/build_hunyuan_real_request_routing_html.py",
        "--trace-dir",
        str(trace_dir),
        "--output-html",
        str(html_path),
        "--output-json",
        str(json_path),
        "--prompt",
        args.prompt,
        "--model",
        args.model,
        "--stage-config",
        str(stage_config),
        "--height",
        str(args.height),
        "--width",
        str(args.width),
        "--steps",
        str(args.steps),
        "--guidance-scale",
        str(args.guidance_scale),
        "--seed",
        str(args.seed),
        "--image-url",
        image_url,
        "--rank-policy",
        args.rank_policy,
    ]
    subprocess.run(build_cmd, cwd=root, check=True)

    if args.publish_dir:
        copy_publish(output_root, Path(args.publish_dir).resolve())
        print(f"Published page files to {args.publish_dir}", flush=True)

    print(f"Output root: {output_root}", flush=True)
    print(f"HTML: {html_path}", flush=True)
    print(f"Trace dir: {trace_dir}", flush=True)
    print(f"Log: {log_path}", flush=True)


if __name__ == "__main__":
    main()
